import type { operations } from "@/types/api";

export type OperationId = keyof operations;
export type ApiAccess = "public" | "auth" | "admin";
export type ApiCoverage = "auto-read" | "manual-action" | "manual-read";
export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export type ApiCatalogItem = {
	operationId: OperationId;
	method: HttpMethod;
	path: string;
	group: string;
	route: string;
	access: ApiAccess;
	coverage: ApiCoverage;
	description: string;
	destructive?: boolean;
};

export const apiCatalog: readonly ApiCatalogItem[] = [
	{
		operationId: "health",
		method: "GET",
		path: "/health",
		group: "Runtime",
		route: "/overview",
		access: "public",
		coverage: "auto-read",
		description: "Process health probe.",
	},
	{
		operationId: "ready",
		method: "GET",
		path: "/health/ready",
		group: "Runtime",
		route: "/overview",
		access: "public",
		coverage: "auto-read",
		description: "Readiness probe.",
	},
	{
		operationId: "system_info",
		method: "GET",
		path: "/api/v1/system/info",
		group: "Runtime",
		route: "/overview",
		access: "public",
		coverage: "auto-read",
		description: "Version, build, and branding information.",
	},
	{
		operationId: "public_example",
		method: "GET",
		path: "/api/v1/examples/public",
		group: "Examples",
		route: "/overview",
		access: "public",
		coverage: "auto-read",
		description: "Public example endpoint.",
	},
	{
		operationId: "protected_example",
		method: "GET",
		path: "/api/v1/examples/protected",
		group: "Examples",
		route: "/overview",
		access: "auth",
		coverage: "manual-read",
		description: "Cookie-or-Bearer authenticated example endpoint.",
	},
	{
		operationId: "check_auth_state",
		method: "GET",
		path: "/api/v1/auth/check",
		group: "Auth",
		route: "/auth",
		access: "public",
		coverage: "auto-read",
		description: "Initial setup/bootstrap state.",
	},
	{
		operationId: "setup_first_admin",
		method: "POST",
		path: "/api/v1/auth/setup",
		group: "Auth",
		route: "/auth",
		access: "public",
		coverage: "manual-action",
		description: "Create the first administrator.",
	},
	{
		operationId: "register",
		method: "POST",
		path: "/api/v1/auth/register",
		group: "Auth",
		route: "/auth",
		access: "public",
		coverage: "manual-action",
		description: "Register a local account.",
	},
	{
		operationId: "login",
		method: "POST",
		path: "/api/v1/auth/login",
		group: "Auth",
		route: "/auth",
		access: "public",
		coverage: "manual-action",
		description: "Issue HttpOnly session cookies.",
	},
	{
		operationId: "refresh_token",
		method: "POST",
		path: "/api/v1/auth/refresh",
		group: "Auth",
		route: "/auth",
		access: "auth",
		coverage: "manual-action",
		description: "Refresh the current cookie session.",
	},
	{
		operationId: "logout",
		method: "POST",
		path: "/api/v1/auth/logout",
		group: "Auth",
		route: "/auth",
		access: "auth",
		coverage: "manual-action",
		description: "Revoke the current cookie session.",
	},
	{
		operationId: "get_current_user",
		method: "GET",
		path: "/api/v1/auth/me",
		group: "Auth",
		route: "/auth",
		access: "auth",
		coverage: "manual-read",
		description: "Load the current authenticated user.",
	},
	{
		operationId: "list_auth_sessions",
		method: "GET",
		path: "/api/v1/auth/sessions",
		group: "Auth",
		route: "/auth",
		access: "auth",
		coverage: "manual-read",
		description: "List current user's sessions.",
	},
	{
		operationId: "list_external_auth_providers",
		method: "GET",
		path: "/api/v1/external-auth/providers",
		group: "External Auth",
		route: "/external-auth",
		access: "public",
		coverage: "auto-read",
		description: "Public external-auth providers.",
	},
	{
		operationId: "start_external_auth_login",
		method: "POST",
		path: "/api/v1/external-auth/{provider}/start",
		group: "External Auth",
		route: "/external-auth",
		access: "public",
		coverage: "manual-action",
		description: "Start public external-auth login.",
	},
	{
		operationId: "finish_external_auth_login",
		method: "GET",
		path: "/api/v1/external-auth/{provider}/callback",
		group: "External Auth",
		route: "/external-auth",
		access: "public",
		coverage: "manual-action",
		description: "Finish public external-auth callback.",
	},
	{
		operationId: "auth_external_auth_list_providers",
		method: "GET",
		path: "/api/v1/auth/external-auth/providers",
		group: "External Auth",
		route: "/external-auth",
		access: "public",
		coverage: "auto-read",
		description: "Auth namespace external-auth providers.",
	},
	{
		operationId: "auth_external_auth_list_providers_by_kind",
		method: "GET",
		path: "/api/v1/auth/external-auth/{kind}/providers",
		group: "External Auth",
		route: "/external-auth",
		access: "public",
		coverage: "manual-read",
		description: "Auth providers filtered by provider kind.",
	},
	{
		operationId: "auth_external_auth_start_login",
		method: "POST",
		path: "/api/v1/auth/external-auth/{kind}/{provider}/start",
		group: "External Auth",
		route: "/external-auth",
		access: "public",
		coverage: "manual-action",
		description: "Start kind-qualified external-auth login.",
	},
	{
		operationId: "auth_external_auth_finish_login",
		method: "GET",
		path: "/api/v1/auth/external-auth/{kind}/{provider}/callback",
		group: "External Auth",
		route: "/external-auth",
		access: "public",
		coverage: "manual-action",
		description: "Finish kind-qualified external-auth callback.",
	},
	{
		operationId: "list_config",
		method: "GET",
		path: "/api/v1/admin/config",
		group: "Admin Config",
		route: "/admin/config",
		access: "admin",
		coverage: "auto-read",
		description: "List runtime config entries.",
	},
	{
		operationId: "config_schema",
		method: "GET",
		path: "/api/v1/admin/config/schema",
		group: "Admin Config",
		route: "/admin/config",
		access: "admin",
		coverage: "auto-read",
		description: "List config schema definitions.",
	},
	{
		operationId: "get_config",
		method: "GET",
		path: "/api/v1/admin/config/{key}",
		group: "Admin Config",
		route: "/admin/config",
		access: "admin",
		coverage: "manual-read",
		description: "Load one config entry by key.",
	},
	{
		operationId: "set_config",
		method: "PUT",
		path: "/api/v1/admin/config/{key}",
		group: "Admin Config",
		route: "/admin/config",
		access: "admin",
		coverage: "manual-action",
		description: "Set a config value.",
	},
	{
		operationId: "delete_config",
		method: "DELETE",
		path: "/api/v1/admin/config/{key}",
		group: "Admin Config",
		route: "/admin/config",
		access: "admin",
		coverage: "manual-action",
		description: "Delete a custom config value.",
		destructive: true,
	},
	{
		operationId: "admin_list_external_auth_provider_kinds",
		method: "GET",
		path: "/api/v1/admin/external-auth/provider-kinds",
		group: "Admin External Auth",
		route: "/admin/external-auth",
		access: "admin",
		coverage: "auto-read",
		description: "List supported provider kinds.",
	},
	{
		operationId: "admin_list_external_auth_providers",
		method: "GET",
		path: "/api/v1/admin/external-auth/providers",
		group: "Admin External Auth",
		route: "/admin/external-auth",
		access: "admin",
		coverage: "auto-read",
		description: "List configured providers.",
	},
	{
		operationId: "admin_create_external_auth_provider",
		method: "POST",
		path: "/api/v1/admin/external-auth/providers",
		group: "Admin External Auth",
		route: "/admin/external-auth",
		access: "admin",
		coverage: "manual-action",
		description: "Create an external-auth provider.",
	},
	{
		operationId: "admin_test_external_auth_provider_params",
		method: "POST",
		path: "/api/v1/admin/external-auth/providers/test",
		group: "Admin External Auth",
		route: "/admin/external-auth",
		access: "admin",
		coverage: "manual-action",
		description: "Test provider parameters before saving.",
	},
	{
		operationId: "admin_get_external_auth_provider",
		method: "GET",
		path: "/api/v1/admin/external-auth/providers/{id}",
		group: "Admin External Auth",
		route: "/admin/external-auth",
		access: "admin",
		coverage: "manual-read",
		description: "Load one provider.",
	},
	{
		operationId: "admin_update_external_auth_provider",
		method: "PATCH",
		path: "/api/v1/admin/external-auth/providers/{id}",
		group: "Admin External Auth",
		route: "/admin/external-auth",
		access: "admin",
		coverage: "manual-action",
		description: "Patch one provider.",
	},
	{
		operationId: "admin_delete_external_auth_provider",
		method: "DELETE",
		path: "/api/v1/admin/external-auth/providers/{id}",
		group: "Admin External Auth",
		route: "/admin/external-auth",
		access: "admin",
		coverage: "manual-action",
		description: "Delete one provider.",
		destructive: true,
	},
	{
		operationId: "admin_test_external_auth_provider",
		method: "POST",
		path: "/api/v1/admin/external-auth/providers/{id}/test",
		group: "Admin External Auth",
		route: "/admin/external-auth",
		access: "admin",
		coverage: "manual-action",
		description: "Test a saved provider.",
	},
	{
		operationId: "admin_list_tasks",
		method: "GET",
		path: "/api/v1/admin/tasks",
		group: "Admin Tasks",
		route: "/admin/tasks",
		access: "admin",
		coverage: "auto-read",
		description: "List background tasks.",
	},
	{
		operationId: "admin_cleanup_tasks",
		method: "POST",
		path: "/api/v1/admin/tasks/cleanup",
		group: "Admin Tasks",
		route: "/admin/tasks",
		access: "admin",
		coverage: "manual-action",
		description: "Remove completed tasks matching filters.",
		destructive: true,
	},
	{
		operationId: "admin_retry_task",
		method: "POST",
		path: "/api/v1/admin/tasks/{id}/retry",
		group: "Admin Tasks",
		route: "/admin/tasks",
		access: "admin",
		coverage: "manual-action",
		description: "Retry a failed task.",
	},
	{
		operationId: "list_audit_logs",
		method: "GET",
		path: "/api/v1/admin/audit-logs",
		group: "Admin Audit",
		route: "/admin/audit",
		access: "admin",
		coverage: "auto-read",
		description: "List audit log entries.",
	},
];

export const apiCatalogByOperation = new Map(
	apiCatalog.map((item) => [item.operationId, item]),
);

export function getApiCatalogStats() {
	const groups = new Set(apiCatalog.map((item) => item.group));
	const admin = apiCatalog.filter((item) => item.access === "admin").length;
	const auth = apiCatalog.filter((item) => item.access === "auth").length;
	const publicCount = apiCatalog.filter(
		(item) => item.access === "public",
	).length;

	return {
		total: apiCatalog.length,
		groups: groups.size,
		admin,
		auth,
		public: publicCount,
	};
}
